version: 2.1

setup: true

orbs: 
  # continuation: circleci/continuation@0.2.0
  path: circleci/path-filtering@0.1.3

workflows:
  check-required-builds:
    jobs:
      - path/filter:
          base-revision: main
          config-path: .circleci/next.yml
          mapping: |
            apps/app1/.* build_app1 true 
            apps/app2/.* build_app2 true 
            apps/app3/.* build_app3 true 
            .circleci/.* trigger_all true
          filters:
            branches:
              ignore:
              - /^integration.*/
              - /^hotfix-integration\/.*/
              - /^prod.*/
              - /^hotfix-prod\/.*/
            
      - path/filter:
          config-path: .circleci/next.yml
          base-revision: prod
          mapping: |
            apps/app1/.* build_app1 true 
            apps/app2/.* build_app2 true 
            apps/app3/.* build_app3 true 
            .circleci/.* trigger_all true
          filters:
            branches:
              only:
              - /^prod.*/
              - /^hotfix-prod\/.*/

